const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Dictionary,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Internationalization,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.OnClicked,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Internationalization.Acts.SetLocale
	];
};
self.C3_JsPropNameTable = [
	{txUsuarioAtivo: 0},
	{Esmaecer: 0},
	{tx_cliqueTreinamentoDesejado: 0},
	{texto2: 0},
	{tx_entrar: 0},
	{tx_simples: 0},
	{tx_ativar_desativar_variaveis: 0},
	{ComoAtualizarOSKU: 0},
	{tx_RobsonSOuza: 0},
	{ComoCriarNovaReceita: 0},
	{AF_logo_2: 0},
	{bt_brasil: 0},
	{bt_china: 0},
	{bt_espanha: 0},
	{bt_italia: 0},
	{bt_usa: 0},
	{AF_logo_: 0},
	{bg_azul: 0},
	{bg_treino_ativar_desativar_variavel: 0},
	{bg_treino_atualizar_SKU: 0},
	{bg_home: 0},
	{Senóide: 0},
	{seta: 0},
	{aveva_: 0},
	{kimberly_: 0},
	{bt_entrar: 0},
	{bg_como_cadastrar_variavel: 0},
	{bg_criar_nova_receita_AFC: 0},
	{inputBox: 0},
	{Mouse: 0},
	{Dic_L_usuarios: 0},
	{Teclado: 0},
	{Navegador: 0},
	{tradutor: 0},
	{AJAX: 0},
	{AF_logo_3: 0},
	{tx10: 0},
	{logo_: 0},
	{bandeiras: 0},
	{usuarioAtivo: 0},
	{IdiomaSelecionado: 0}
];

self.InstanceType = {
	txUsuarioAtivo: class extends self.ITextInstance {},
	tx_cliqueTreinamentoDesejado: class extends self.ITextInstance {},
	texto2: class extends self.ITextInstance {},
	tx_entrar: class extends self.ITextInstance {},
	tx_simples: class extends self.ITextInstance {},
	tx_ativar_desativar_variaveis: class extends self.ITextInstance {},
	ComoAtualizarOSKU: class extends self.ITextInstance {},
	tx_RobsonSOuza: class extends self.ITextInstance {},
	ComoCriarNovaReceita: class extends self.ITextInstance {},
	AF_logo_2: class extends self.ISpriteInstance {},
	bt_brasil: class extends self.ISpriteInstance {},
	bt_china: class extends self.ISpriteInstance {},
	bt_espanha: class extends self.ISpriteInstance {},
	bt_italia: class extends self.ISpriteInstance {},
	bt_usa: class extends self.ISpriteInstance {},
	AF_logo_: class extends self.ISpriteInstance {},
	bg_azul: class extends self.ISpriteInstance {},
	bg_treino_ativar_desativar_variavel: class extends self.ISpriteInstance {},
	bg_treino_atualizar_SKU: class extends self.ISpriteInstance {},
	bg_home: class extends self.ISpriteInstance {},
	seta: class extends self.ISpriteInstance {},
	aveva_: class extends self.ISpriteInstance {},
	kimberly_: class extends self.ISpriteInstance {},
	bt_entrar: class extends self.ISpriteInstance {},
	bg_como_cadastrar_variavel: class extends self.ISpriteInstance {},
	bg_criar_nova_receita_AFC: class extends self.ISpriteInstance {},
	inputBox: class extends self.ITextInputInstance {},
	Mouse: class extends self.IInstance {},
	Dic_L_usuarios: class extends self.IDictionaryInstance {},
	Teclado: class extends self.IInstance {},
	Navegador: class extends self.IInstance {},
	tradutor: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	AF_logo_3: class extends self.ISpriteInstance {},
	tx10: class extends self.ITextInstance {},
	logo_: class extends self.ISpriteInstance {},
	bandeiras: class extends self.ISpriteInstance {}
}